version: '3'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:1.0.0
    container_name: oracle-db
    volumes:
      - ./scripts:/scripts
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - 1521:1521
      - 5500:5500
